-- The mark of a listed instrument (a share or a fund), stored as bytes so the browser never
-- fetches a third-party URL and a rebuild of the container loses nothing (issue #162).
--
-- Global reference data, keyed by ticker rather than by member or account: the same AAPL held in
-- two accounts, or by two members, is one row. Nothing references this table and nothing cascades
-- into it, on purpose -- a position being sold must never delete a mark another holding still
-- shows, and an orphan costs a few kilobytes.
--
-- One row per ticker that was *attempted*, not just per ticker that resolved: the status is the
-- miss marker that stops a permanent miss from being re-fetched on every price pass (the
-- requisition.logo_backfill_attempted_at precedent).
--   STORED  image present; dark variant optional (a mark drawn for a dark background).
--   ABSENT  the source answered and has no usable mark. Never retried.
--   FAILED  the source did not answer (5xx, timeout). Retried after a cool-off.
CREATE TABLE instrument_logo (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker            VARCHAR(30)  NOT NULL,
    status            VARCHAR(16)  NOT NULL,
    image             BYTEA,
    content_type      VARCHAR(32),
    image_dark        BYTEA,
    content_type_dark VARCHAR(32),
    attempted_at      TIMESTAMPTZ  NOT NULL,
    fetched_at        TIMESTAMPTZ,
    CONSTRAINT uk_instrument_logo_ticker UNIQUE (ticker),
    CONSTRAINT ck_instrument_logo_status CHECK (status IN ('STORED', 'ABSENT', 'FAILED')),
    -- A STORED row without bytes would hand the UI a URL that 404s on every render; any other
    -- status carrying bytes would be a mark nobody serves.
    CONSTRAINT ck_instrument_logo_stored_image CHECK (
        (status = 'STORED') = (image IS NOT NULL AND content_type IS NOT NULL AND fetched_at IS NOT NULL)
    ),
    CONSTRAINT ck_instrument_logo_dark_pair CHECK ((image_dark IS NULL) = (content_type_dark IS NULL))
);
